[package]
name = "youi"
version = "0.1.0"


bench = [
    "lazy",
]

[dependencies]
youi-core = { version = "0.1.0", path = "./youi-core"}
youi-sqlite = { version = "0.1.0", path = "./youi-sqlite"}
youi-app-config = {version = "0.1.0", path = "./youi-app-config"}

[lib]
bench = false